name: allplant
description: "An easy to use plant care app"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.8.0-24.0.dev


dependencies:
  flutter:
    sdk: flutter

  #hive
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1

  path_provider: ^2.1.0

  #router
  go_router: ^14.8.1

  #graph
  fl_chart: ^0.70.2


  cupertino_icons: ^1.0.8

   #very good analysis
  very_good_analysis: ^7.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0
  build_runner: ^2.4.15



flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
      - assets/images/
  #   - images/a_dot_ham.jpeg

 
  fonts:
    - family: Montserrat
      fonts:
          - asset: fonts/Montserrat-MediumItalic.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
